; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_port = /dev/ttyUSB0
upload_flags =
    --before=default_reset
    --after=hard_reset
    --chip=esp8266
lib_deps =
    painlessmesh/painlessMesh@^1.5.0
    bblanchon/ArduinoJson@^6.21.3
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit BMP085 Library@^1.2.2
    adafruit/Adafruit Unified Sensor@^1.1.9
build_flags = 
    -D STATIC_NODE_ID=3
    -D GATEWAY_NODE_ID=1

[env:gateway]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_port = /dev/ttyUSB0
upload_flags =
    --before=default_reset
    --after=hard_reset
    --chip=esp8266
lib_deps =
    painlessmesh/painlessMesh@^1.5.0
    bblanchon/ArduinoJson@^6.21.3
    adafruit/DHT sensor library@^1.4.4
build_flags = 
    -D STATIC_NODE_ID=1
    -D GATEWAY_NODE_ID=1

[env:bmp085_node]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0
upload_timeout = 60
build_flags = 
    -D STATIC_NODE_ID=4
    -D GATEWAY_NODE_ID=1
    -D USE_BMP085
lib_deps =
    painlessmesh/painlessMesh@^1.5.0
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit BMP085 Library@^1.2.2
    adafruit/Adafruit Unified Sensor@^1.1.9